### ISSUE TITLE
MigrateToMpl creates master edition with `None` supply, allowing unlimited prints

### ISSUE THREAD

**Issue by omarkilani** [magiceden-oss/open_creator_protocol#64]
Hey @nothing0012,

I'm not sure whether this is intentional or not, but I believe that instead of `None`, this line should be `Some(0)`.

https://github.com/magiceden-oss/open_creator_protocol/blob/main/programs/open_creator_protocol/src/instructions/nft_proxy/migrate_to_mpl.rs#L138

C.f. https://docs.metaplex.com/programs/token-metadata/accounts#master-edition

> The optional Max Supply field of the Master Edition account tells us how many copies of the NFT can be created. When set to None, an unlimited amount of copies can be created. When set to zero, the NFT cannot be copied.

(Noticed this on a Bonkz de-OCPification tx showing Max Supply = NULL: https://solscan.io/tx/2YVN7vWDdu5gEwNfC3mFaJohowhnkZ76iKju53RWP3BUiqcgEy29xySnwE5BNmbh1tNXaGe899N2P7C5doiarhaG )

**Comment by nothing0012** [comment]
thank you so much for the report @omarkilani ! we've just deployed the change https://github.com/magiceden-oss/open_creator_protocol/pull/65
